using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace practice.jd.HackerRank
{
    public class BtwnTwoSets
    {
        // this was generated by ChatGPT
        public static int getTotalX(List<int> a, List<int> b)
        {
            int lcmA = a.Aggregate((x, y) => LCM(x, y));
            int gcdB = b.Aggregate((x, y) => GCD(x, y));

            int result = 0;
            for (int x = lcmA; x <= gcdB; x += lcmA)
            {
                if (gcdB % x == 0) result++;
            }
            return result;
        }
        public static int GCD(int a, int b)
        {
            while (b != 0)
            {
                int temp = b;
                b = a % b;
                a = temp;
            }
            return a;
        }
        public static int LCM(int a, int b)
        {
            return (a * b) / GCD(a, b);
        }
    }
}
